<a href="https://colab.research.google.com/github/Jessenia12/-mapa/blob/main/NumPy_Exercises_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Exercises for Data Analysis

In [1]:
# 1. Import numpy as np and see the version
import numpy as np
print("Versión de NumPy:", np.__version__)

Versión de NumPy: 2.0.2


In [2]:
# 2. Create a 1D array of numbers from 0 to 9
arr = np.arange(10)
print("\nEjercicio 2 - Array del 0 al 9:")
print(arr)


Ejercicio 2 - Array del 0 al 9:
[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 3. Create a 3×3 numpy array of all True’s
arr_true = np.full((3, 3), True, dtype=bool)
print("\nEjercicio 3 - Array 3x3 de True's:")
print(arr_true)


Ejercicio 3 - Array 3x3 de True's:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
# 4. Extract all odd numbers from arr
arr = np.arange(10)
arr_impares = arr[arr % 2 == 1]
print("\nEjercicio 4 - Números impares:")
print(arr_impares)


Ejercicio 4 - Números impares:
[1 3 5 7 9]


In [6]:
# 5. Replace all odd numbers in arr with -1
arr = np.arange(10)
arr[arr % 2 == 1] = -1
print("\nEjercicio 5 - Array con impares reemplazados por -1:")
print(arr)


Ejercicio 5 - Array con impares reemplazados por -1:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [7]:
#  6. Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)  # -1 calcula automáticamente las columnas
print("\nEjercicio 6 - Array 1D convertido a 2D (2 filas):")
print(arr_2d)


Ejercicio 6 - Array 1D convertido a 2D (2 filas):
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
#  7. Stack arrays a and b vertically
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
resultado_vertical = np.vstack([a, b])
# Alternativa: resultado_vertical = np.concatenate([a, b], axis=0)
print("\nEjercicio 7 - Arrays apilados verticalmente:")
print(resultado_vertical)


Ejercicio 7 - Arrays apilados verticalmente:
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [9]:
#  8. Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2, -1)
b = np.repeat(1, 10).reshape(2, -1)
resultado_horizontal = np.hstack([a, b])
# Alternativa: resultado_horizontal = np.concatenate([a, b], axis=1)
print("\nEjercicio 8 - Arrays apilados horizontalmente:")
print(resultado_horizontal)


Ejercicio 8 - Arrays apilados horizontalmente:
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [10]:
#  9. Get all items between 5 and 10 from a.
# your code here
import numpy as np
a = np.arange(15)
resultado = a[(a >= 5) & (a <= 10)]
print("\nEjercicio 9 - Elementos entre 5 y 10:")
print(resultado)


Ejercicio 9 - Elementos entre 5 y 10:
[ 5  6  7  8  9 10]


In [11]:
#  10. How to make a python function that handles scalars to work on numpy arrays?
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# Vectorizar la función
pair_max = np.vectorize(maxx)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
resultado = pair_max(a, b)
print("\nEjercicio 10 - Máximo por pares:")
print(resultado)


Ejercicio 10 - Máximo por pares:
[6 7 9 8 9 7 5]


In [12]:
#  11. Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
arr = np.arange(9).reshape(3, 3)
print("\nEjercicio 11 - Array original:")
print(arr)
arr[:, [1, 2]] = arr[:, [2, 1]]
print("Array con columnas 1 y 2 intercambiadas:")
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Ejercicio 11 - Array original:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array con columnas 1 y 2 intercambiadas:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [13]:
#  12. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# Hint
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]
arr_random = np.random.uniform(5, 10, size=(5, 3))
# Alternativa: arr_random = np.random.rand(5, 3) * 5 + 5
print("\nEjercicio 12 - Array 5x3 con números aleatorios entre 5 y 10:")
print(arr_random)


Ejercicio 12 - Array 5x3 con números aleatorios entre 5 y 10:
[[8.35614607 8.64404323 7.18124188]
 [6.77841121 7.20259062 7.18685459]
 [6.55348164 7.18606271 6.47977011]
 [6.28185798 8.02428876 5.98351126]
 [6.02945367 9.84032873 8.02745242]]
